- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
- src/compilerOptions.test.ts
- src/nodes/typeGuards.test.ts
- src/syntax.test.ts
- src/types/typeGuards.test.ts
Adding https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/237 here too.
If we bundle esm, this isn't needed but it's still nice to enforce a consistent style.
> chore: enable import/extensions ESLint rule

- .github/workflows/release.yml
> docs: fix broken link

- src/nodes/typeGuards/single.ts
Type guards for a bunch of the keyword nodes
> feat: add missing keyword token nodes

- src/nodes/typeGuards/union.ts
> style: add blank lines between functions

- .github/workflows/release.yml
- package.json
> ci: fix release workflow permissions

- README.md
The h1 title of README.md was changed from "TypeScript API Tools" to "TypeScript API Utils" to match the updated package name
> fix: update README h1 title to match package name

- .github/renovate.json
> chore: prefix "dependencies" with "area: "

- .github/workflows/release.yml
- package.json
> ci: only run one release workflow at a time

- .github/workflows/release-docs.yml
> ci: fix up and allow manual running of workflow

- .github/workflows/release-docs.yml
> ci: fix setting and reading of environment variable

- .github/workflows/release-docs.yml
> chore: ci: switch to single quotes

- .github/workflows/release-docs.yml
- .github/workflows/release.yml
> chore: ci: change triggers for releasing docs

- .github/workflows/release-docs.yml
> chore: ci: ignore missing old docs

- .github/workflows/release-docs.yml
> chore: ci: use prepare action

- .github/workflows/release-docs.yml
> chore: ci: fix PACKAGE_VERSION env var

- .github/workflows/release-docs.yml
> chore: ci: remove unneeded line

- .github/workflows/release-docs.yml
> chore: ci: fix line breaks

- .github/actions/protection-main/action.yml
- .github/actions/unprotect-main/action.yml
- .github/workflows/release-docs.yml
- .github/workflows/release.yml
> chore: ci: fix branch protection issue

- .github/workflows/release.yml
> chore: ci: fix path issue

- .github/actions/protection-main/action.yml
- .github/actions/unprotect-main/action.yml
- .github/workflows/release-docs.yml
- .github/workflows/release.yml
> chore: ci: fix secrets

- src/types/typeGuards/simple.test.ts
- src/types/typeGuards/simple.ts
- src/types/utilities.ts
Removes the function and refactors things that used it.
> fix: remove isLiteralType

- .github/workflows/release.yml
> ci: fix setting of env var

- .github/workflows/release-docs.yml
- .github/workflows/release.yml
> ci: fix calling of release-docs for release

- .github/workflows/release.yml
> ci: fix permissions

- .github/workflows/release.yml
> ci: update comparison

- .github/workflows/release-docs.yml
- .github/workflows/release.yml
> ci: fix concurrency deadlock

- .github/workflows/release-docs.yml
> ci: fix testing of UP_TO_DATE

- src/modifiers.ts
> fix: rename hasModifier to includesModifier

- src/types/utilities.ts
> fix: remove someTypePart

- knip.jsonc
- package.json
- pnpm-lock.yaml
> chore(deps): update knip to v1.14.1

- package.json
> chore: v0.0.40

- .github/renovate.json
> chore: have renovatebot auto dedupe when updating deps

- package.json
> chore: v0.0.41

- .eslintignore
> chore: have eslint ignore generated doc files

- src/modifiers.ts
> docs: correct example text for includesModifier

- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
- src/compilerOptions.ts
Manually doing these all together.
> chore: update typescript dependencies to latest

- package.json
- pnpm-lock.yaml
Swaps the dependency over and re-runs `pnpm`.
> build: switch from http-serve to http-server

- .vscode/settings.json
Small update to vscode settings for eslint.
> chore: update settings for eslint plugin update

- .github/workflows/release.yml
Seem like a bit to much of this workflow file was removed when the release notes were separated from it.
> ci: fix ci release workflow

- .github/workflows/release.yml
> chore: add missing release.yml permissions

- .github/renovate.json
- package.json
- pnpm-lock.yaml
> build: specify max allowed versions of dependencies

- .github/workflows/gh-pages-sync-workflows.yml
> ci: fix up

- .github/workflows/gh-pages-sync-workflows.yml
> chore: revert "ci: fix up (#582)"

- .github/workflows/docs-release.yml
> ci: fix up releasing the docs

- package.json
> build: set package.json version to latest release

- pnpm-lock.yaml
Fix [Lint Packages / lint_packages](https://github.com/JoshuaKGoldberg/ts-api-utils/actions/runs/13158654638/job/36721568885) on main branch
> chore: run pnpm dedupe
