JoshuaKGoldberg/ts-api-utils

.all-contributorsrc
README.md
cspell.json
package.json
pnpm-lock.yaml
src/compilerOptions.test.ts
src/index.test.ts
src/nodes/typeGuards.test.ts
src/syntax.test.ts
src/test/utils.ts
src/types/typeGuards.test.ts
vitest.config.ts

Adds tests, including usage of [`@typescript/vfs`](https://www.npmjs.com/package/@typescript/vfs) for type system tests.

test: added first unit tests

---

.all-contributorsrc
.github/CONTRIBUTING.md
.github/DEVELOPMENT.md
.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/01-bug.yaml
.github/ISSUE_TEMPLATE/02-documentation.yaml
.github/ISSUE_TEMPLATE/03-feature.yaml
.github/ISSUE_TEMPLATE/04-tooling.yaml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release.yml
README.md
package.json
vitest.config.ts

Renames the package with a find-and-replace. Also changes the suggested import from `* as tools` to `* as tsutils`.

chore: rename to ts-api-utils

---

src/comments.ts
src/nodes/utilities.ts
src/types/getters.ts
src/types/utilities.ts

Adds missing `.js` extensions where needed.

fix: add missing explicit .js extensions to imports

---

src/tokens.ts

`JSDoc` is the replacement for `JSDocComment` .
```ts
ts.SyntaxKind.JSDoc === ts.SyntaxKind.JSDocComment
```

refactor: use `JSDoc` over `JSDocComment`

---

src/comments.ts

refactor: use nullish coalescing instead of or operator

---

src/types/utilities.test.ts
src/types/utilities.ts

Checks if `type.modifiersType` exists before asking `isPropertyReadonlyInType(modifiersType, ...)`.
This is a recreation of https://github.com/ajafff/tsutils/pull/136. Which means 😄:
Co-authored-by: @kirjs

fix: account for mapped types without modifiers in isPropertyReadonlyInType

---

src/nodes/typeGuards/compound.ts

re https://github.com/JoshuaKGoldberg/ts-api-utils/pull/16#discussion_r1106671329
Looking at how TypeScript internally uses `NamedDeclaration`, it is simply used for casting a `Declaration` to allow accessing the `name` property.
The only reason the `name` property seems to be optional, is to handle the case of a non-named `Declaration` being cast to `NamedDeclaration`.
In terms how an `isNamedDeclaration` type guard would practically work, the `name` property should be required. This means well have to use a slightly different type than ts's `NamedDeclaration`. This PR adds that type guard with makes such a change in the type being guarded.

feat: add isNamedDeclaration

---

.github/workflows/release-docs.yml
.github/workflows/release.yml
.prettierignore
cspell.json

chore: ci: only push coverage changes when running after a release

---

.github/workflows/release-docs.yml
.github/workflows/release.yml

ci: refactor release ci

---

package.json

build: fix types for cjs

---

src/nodes/typeGuards/compound.ts

refactor: use `StringLiteralLike` over `StringLiteral | SubstitutionTemplateLiteral`

---

cspell.json
package.json
pnpm-lock.yaml
typedoc.json

Directly uses [`typedoc-plugin-konamimojisplosion`](https://github.com/JoshuaKGoldberg/typedoc-plugin-konamimojisplosion) with no configuration.

docs: add typedoc-plugin-konamimojisplosion

---

README.md

Especially now that the README.md is teeny, I don't think there's much of a need to have _two_ explicit `tsutils` mentions.

docs: leaner tsutils notice in README.md

---

docs/index.md

Adds a few explanatory lines and a canonical function example to the docs.

docs: added introduction to docs site

---

.eslintrc.cjs
package.json
pnpm-lock.yaml
src/comments.ts
src/compilerOptions.ts
src/flags.ts
src/modifiers.ts
src/nodes/typeGuards/compound.ts
src/nodes/typeGuards/single.ts
src/nodes/typeGuards/union.ts
src/scopes.ts
src/syntax.ts
src/tokens.ts
src/types/getters.ts
src/types/typeGuards/compound.ts
src/types/typeGuards/objects.ts
src/types/typeGuards/simple.ts
src/types/utilities.ts

Sets up `eslint-plugin-jsdoc` and apply whitespace fixes for violations reported.

chore: setup eslint-plugin-jsdoc to lint jsdoc

---

.eslintrc.cjs
package.json
pnpm-lock.yaml
src/comments.ts
src/compilerOptions.test.ts
src/compilerOptions.ts
src/flags.ts
src/modifiers.ts
src/nodes/typeGuards/compound.test.ts
src/nodes/typeGuards/compound.ts
src/nodes/typeGuards/single.ts
src/nodes/typeGuards/union.ts
src/nodes/utilities.ts
src/scopes.ts
src/syntax.test.ts
src/syntax.ts
src/tokens.ts
src/types/getters.test.ts
src/types/getters.ts
src/types/typeGuards/compound.test.ts
src/types/typeGuards/compound.ts
src/types/typeGuards/objects.ts
src/types/typeGuards/simple.test.ts
src/types/utilities.test.ts
src/types/utilities.ts
src/utils.ts

Use `import ts from "typescript"` instead of `import * as ts from "typescript"`.
Also adds eslint rule [`unicorn/import-style`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/import-style.md) to enforce this.

fix: import typescript using default

---

src/nodes/typeGuards/union.ts

fix: remove "is" from function name that start with "isHas"

---

src/types/utilities.ts

Adds the utility as a counterpart to `unionTypeParts`.

feat: add intersectionTypeParts utility

---

src/comments.ts
src/types/typeGuards/intrinsic.ts
src/types/utilities.ts

docs: fix function names used in examples

---

src/types/typeGuards/intrinsic.ts

fix #226
adds `isIntrinsicErrorType`

feat: add isIntrinsicErrorType

---

src/comments.test.ts
src/nodes/typeGuards/union.test.ts
src/types/getters.test.ts
src/types/typeGuards/literal.test.ts
src/types/typeGuards/single.test.ts
src/types/utilities.test.ts

It's been bugging me that this package now has >2.5 million downloads but only has 46% coverage. Which Codecov shows as a red color in the badge. 😡 
No end user impacts here. Just added test coverage.

test: add a few more unit tests

---

src/types/utilities.ts

Adds in a shallow `typeParts` function. It's roughly equivalent to the existing `intersectionTypeParts` and `unionTypeParts` functions.
Doesn't add in a `{ recursive?: boolean }` or anything like that.

feat: add typeParts function

---

package.json

Reduces the number in the `package.json` `engines` field.

fix: downgrade engines.node to >=16

---

src/nodes/access.test.ts
src/nodes/access.ts
src/nodes/index.ts

Adds the function, with some rudimentary unit tests.

feat: add getAccessKind

---

src/types/utilities.test.ts
src/types/utilities.ts

The `type.value` returns a `PseudoBigInt` object rather than an actual bigint for TS legacy support reasons. Therefore, to determine if a literal is a falsy value, we cannot rely on the truthiness of `type.value` alone, and need to check what the actual object is if it's not a primitive.

fix: make `isFalsyType()` return `true` for `0n`

---

.github/actions/prepare/action.yml
knip.jsonc
package.json
pnpm-lock.yaml
src/nodes/access.test.ts
src/nodes/typeGuards/compound.ts
src/types/utilities.ts
src/usage/UsageWalker.ts
src/usage/utils.ts
typings/typescript.d.ts

Not required once #531 is merged was node 16 support is dropped there.
Does some of the same things as that PR.
fix #548

build: fix for node 16

---

src/types/typeGuards/literal.test.ts
src/types/typeGuards/literal.ts

Ostensibly, this is the code change, but it looks pretty intentional that it was written this way in the first place, so.... maybe needs some more investigation in order to understand why it was written this way.
<s>I'm not really sure how to test for this, either. I've written a test that proves the bug's existence, but wouldn't prevent it from regressing. Open to suggestions 🤔</s> I've written a test that proves the bug's existence at runtime, _and_ will cause a type-checking error if the `value` field is added back, due to its use of `@ts-expect-error`

fix: remove `.value` field from type declarations for boolean literal types

---

.github/workflows/gh-pages-sync-workflows.yml

This allows trigger from there to run ci workflows.
related to #580
fix #000

ci: sync workflows to the gh-pages branch

---

tsup.config.ts

Turns off the ESBuild bundling that was done with tsup. It was including packages from `node_modules/`. 😩 
Running `du -sh lib/`:
* Baseline (`main`): 1.1M
* With this change: 184K
❤️‍🔥

build: shrink size of bundle

---

src/types/typeGuards/literal.ts

Straightforward removal. These weren't tested, so unit test coverage gets a nice little bump too.
🔪

feat!: remove deprecated literals logic

---

src/comments.test.ts

Raises test coverage by about 3%.
Also removes a `isTsVersionAtLeast` that's unnecessary as of #531. 
💖

test: fill in test coverage for comments.ts

---

.github/workflows/release.yml

I checked https://github.com/actions/upload-pages-artifact/releases and it _seems_ like there's nothing else to update?
💖

chore: bump actions/upload-pages-artifact to v3

---

src/test/utils.ts

This is a small follow-up to https://github.com/JoshuaKGoldberg/ts-api-utils/pull/698#discussion_r1937536540, and it adjusts the test helper `createSourceFileAndTypeChecker` to check that passed syntax is valid (to prevent accidental invalid syntax on test cases).
I've checked locally that this would fail before the change on the linked comment.
---
Codecov fails on this, but I don't think there's much to do (it's a test helper, should it even be included in the codecov report?).

test: adjust `createSourceFileAndTypeChecker` to verify passed code has valid syntax
